### ISSUE TITLE
socket.timeout: timed out after Waiting for PDU...

### ISSUE THREAD

**Issue by SergeSpinoza** [python-smpplib/python-smpplib#106]
Hi. I have problem (use python 3.7), with socket.timeout: 

```
INFO:smpplib.client:Connecting to my-domain.com:7779...
DEBUG:smpplib.client:Receiver mode
DEBUG:smpplib.client:Sending bind_transceiver PDU
DEBUG:smpplib.client:>>b'00000026000000090000000000000001676f6970736d730076396e3862364247000034000000' (38 bytes)
DEBUG:smpplib.client:Waiting for PDU...
Traceback (most recent call last):
  File "/Users/spinoza/Git/_my/telegram-sms-bot/venv/lib/python3.7/site-packages/smpplib/client.py", line 135, in _bind
    resp = self.read_pdu()
  File "/Users/spinoza/Git/_my/telegram-sms-bot/venv/lib/python3.7/site-packages/smpplib/client.py", line 205, in read_pdu
    raw_len = self._socket.recv(4)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/spinoza/Git/_my/telegram-sms-bot/smsbot.py", line 23, in <module>
    client.bind_transceiver(system_id='xxxxxxxxx', password='xxxxxxxxxxx')
  File "/Users/spinoza/Git/_my/telegram-sms-bot/venv/lib/python3.7/site-packages/smpplib/client.py", line 157, in bind_transceiver
    return self._bind('bind_transceiver', **kwargs)
  File "/Users/spinoza/Git/_my/telegram-sms-bot/venv/lib/python3.7/site-packages/smpplib/client.py", line 137, in _bind
    raise exceptions.ConnectionError()
smpplib.exceptions.ConnectionError
WARNING:smpplib.client:<smpplib.client.Client object at 0x1106086d0> was not closed

Process finished with exit code 1
```

I use SMPP in GoIP4 GSM gate. 

What could be the problem?

Thanks.

**Comment by SergeSpinoza** [comment]
I fix this, but have other error: 

```
INFO:smpplib.client:Connecting to my-domain.com:7779...
DEBUG:smpplib.client:Receiver mode
DEBUG:smpplib.client:Sending bind_transceiver PDU
DEBUG:smpplib.client:>>b'00000026000000090000000000000001676f6970736d73003132333435363738000034000000' (38 bytes)
DEBUG:smpplib.client:Waiting for PDU...
DEBUG:smpplib.client:<<b'00000017800000090000000000000001676f6970736d73' (23 bytes)
Traceback (most recent call last):
  File "/Users/spinoza/Git/_my/telegram-sms-bot/smsbot.py", line 23, in <module>
    client.bind_transceiver(system_id='xxxxxxxx', password='xxxxxxxx')
  File "/Users/spinoza/Git/_my/telegram-sms-bot/venv/lib/python3.7/site-packages/smpplib/client.py", line 157, in bind_transceiver
    return self._bind('bind_transceiver', **kwargs)
  File "/Users/spinoza/Git/_my/telegram-sms-bot/venv/lib/python3.7/site-packages/smpplib/client.py", line 135, in _bind
    resp = self.read_pdu()
  File "/Users/spinoza/Git/_my/telegram-sms-bot/venv/lib/python3.7/site-packages/smpplib/client.py", line 225, in read_pdu
    pdu = smpp.parse_pdu(raw_pdu, client=self)
  File "/Users/spinoza/Git/_my/telegram-sms-bot/venv/lib/python3.7/site-packages/smpplib/smpp.py", line 45, in parse_pdu
    new_pdu.parse(data)
  File "/Users/spinoza/Git/_my/telegram-sms-bot/venv/lib/python3.7/site-packages/smpplib/pdu.py", line 131, in parse
    self.parse_params(data[16:])
  File "/Users/spinoza/Git/_my/telegram-sms-bot/venv/lib/python3.7/site-packages/smpplib/command.py", line 314, in parse_params
    self.parse_optional_params(data[pos:])
  File "/Users/spinoza/Git/_my/telegram-sms-bot/venv/lib/python3.7/site-packages/smpplib/command.py", line 329, in parse_optional_params
    field = get_optional_name(type_code)
  File "/Users/spinoza/Git/_my/telegram-sms-bot/venv/lib/python3.7/site-packages/smpplib/command.py", line 72, in get_optional_name
    raise exceptions.UnknownCommandError('Unknown SMPP command code "0x%x"' % code)
smpplib.exceptions.UnknownCommandError: Unknown SMPP command code "0x676f"
WARNING:smpplib.client:<smpplib.client.Client object at 0x10ff81490> was not closed

Process finished with exit code 1

```

**Comment by micartey** [comment]
How did you fix the first issue?
And how do you expect someone to help without providing the source?
