### ISSUE TITLE
TAG: its_session_info, struct.error: required argument is not an integer

### ISSUE THREAD

**Issue by drhidians** [python-smpplib/python-smpplib#112]
Hi, I am using python3.6
Using this chunk of code
```
parts, encoding_flag, msg_type_flag = smpplib.gsm.make_parts(u'Привет мир!\n'*1)
r_pdu = client.send_message(
        source_addr_ton=smpplib.consts.SMPP_TON_INTL,
        #source_addr_npi=smpplib.consts.SMPP_NPI_ISDN,
        # Make sure it is a byte string, not unicode:
        source_addr='******',
        service_type ="USSD",
        ussd_service_op = 0x11,

        its_session_info =b'\x00\x01',
        dest_addr_ton=smpplib.consts.SMPP_TON_INTL,
        #dest_addr_npi=smpplib.consts.SMPP_NPI_ISDN,
        # Make sure thease two params are byte strings, not unicode:
        #Test Code
        destination_addr='******',
        short_message=parts[0],

        data_coding=encoding_flag,
        esm_class=msg_type_flag,
        registered_delivery=True,
    )
```

Getting this:

```
Traceback (most recent call last):
  File "main.py", line 77, in <module>
    client.listen()
  File "/home/pythonsmpp/smpplib/client.py", line 343, in listen
    self.read_once(ignore_error_codes, auto_send_enquire_link)
  File "/home/pythonsmpp/smpplib/client.py", line 315, in read_once
    self._message_received(pdu)
  File "/home/pythonsmpp/smpplib/client.py", line 244, in _message_received
    status = self.message_received_handler(pdu=pdu)
  File "main.py", line 31, in deliver_sm
    registered_delivery=True,
  File "/home/pythonsmpp/smpplib/client.py", line 357, in send_message
    self.send_pdu(ssm)
  File "/home/pythonsmpp/smpplib/client.py", line 181, in send_pdu
    generated = p.generate()
  File "/home/pythonsmpp/smpplib/pdu.py", line 136, in generate
    body = self.generate_params()
  File "/home/pythonsmpp/smpplib/command.py", line 126, in generate_params
    value = self._generate_int_tlv(field)
  File "/home/pythonsmpp/smpplib/command.py", line 202, in _generate_int_tlv
    value = struct.pack(">HH" + fmt, field_code, field_length, data)
struct.error: required argument is not an integer
WARNING:smpp.Client.139658711658224:<smpplib.client.Client object at 0x7f04d3e5eef0> was not closed
```
Could you help me?

Thanks in advance..

**Comment by eigenein** [comment]
Hi David,

Looks like it's a kind of a bug. We should've defined this field as an octet string (SMPP specs, 4.8.4.34), however it's defined as an integer: https://github.com/python-smpplib/python-smpplib/blob/master/smpplib/command.py#L782

For now it should work to provide an integer instead which corresponds to your binary string, big-endian, so just `1`:

```python
its_session_info=1,
```

Could you try that?

**Comment by drhidians** [comment]
Now I am getting form smsc such error:
```
DEBUG:smpp.Client.139761759809320:Read submit_sm_resp PDU
Traceback (most recent call last):
  File "main.py", line 77, in <module>
    client.listen()
  File "/home/pythonsmpp/smpplib/client.py", line 343, in listen
    self.read_once(ignore_error_codes, auto_send_enquire_link)
  File "/home/pythonsmpp/smpplib/client.py", line 306, in read_once
    int(pdu.status),
smpplib.exceptions.PDUError: ('(196) submit_sm_resp: Invalid Optional Parameter Value', 196)
WARNING:smpp.Client.139761759809320:<smpplib.client.Client object at 0x7f1cd20bef28> was not closed

```

**Comment by eigenein** [comment]
Aha, so now the request is successfully sent but SMSC didn't like some parameter value. That's better to check with your SMSC provider actually, I can't see what's wrong from the first sight. You should've got a hexadecimal representation of SubmitSM PDU that you've sent, this may be useful to check with SMSC guys.

@podshumok Do you have any experience with USSD?

**Comment by podshumok** [comment]
no, sorry, unfortunately I'm useless here

**Comment by gunjanbagde** [comment]
Can somebody ans this question?
how-to-set-optional-tlv-parameter-for-submit-sm

https://stackoverflow.com/questions/73221229/using-smpplib-how-to-set-optional-tlv-parameter-for-submit-sm
