### ISSUE TITLE
object has no attribute 'receipted_message_id'

### ISSUE THREAD

**Issue by EugeneBogush** [python-smpplib/python-smpplib#117]
Hi,
I testing smpplib with osmocom msc and received next error after sending message:
```
host:~/work/python-smpplib$ python example.py 
INFO:smpp.Client.140661104894736:Connecting to 192.168.15.240:2775...
DEBUG:smpp.Client.140661104894736:Receiver mode
DEBUG:smpp.Client.140661104894736:Sending bind_transceiver PDU
DEBUG:smpp.Client.140661104894736:>>000000210000000900000000000000014555475f53455256455200000034000000 (33 bytes)
DEBUG:smpp.Client.140661104894736:Waiting for PDU...
DEBUG:smpp.Client.140661104894736:<<0000001180000009000000000000000100 (17 bytes)
DEBUG:smpp.Client.140661104894736:Read bind_transceiver_resp PDU
DEBUG:smpp.Client.140661104894736:Sending submit_sm PDU
DEBUG:smpp.Client.140661104894736:>>0000008d0000000400000000000000020001013131313100010132303038000000000000010000006448656c6c6f206575670a48656c6c6f206575670a48656c6c6f206575670a48656c6c6f206575670a48656c6c6f206575670a48656c6c6f206575670a48656c6c6f206575670a48656c6c6f206575670a48656c6c6f206575670a48656c6c6f206575670a (141 bytes)
2
DEBUG:smpp.Client.140661104894736:Waiting for PDU...
DEBUG:smpp.Client.140661104894736:<<000000278000000400000000000000026d73675f69645f6e6f745f696d706c656d656e74656400 (39 bytes)
DEBUG:smpp.Client.140661104894736:Read submit_sm_resp PDU
sent 2 msg_id_not_implemented
DEBUG:smpp.Client.140661104894736:Waiting for PDU...
DEBUG:smpp.Client.140661104894736:<<0000001f000001020000000076a67633030132303038000000000422000100 (31 bytes)
DEBUG:smpp.Client.140661104894736:Read alert_notification PDU
Traceback (most recent call last):
  File "example.py", line 46, in <module>
    client.listen()
  File "/home/yevhen/work/python-smpplib/smpplib/client.py", line 380, in listen
    self.read_once(ignore_error_codes, auto_send_enquire_link)
  File "/home/yevhen/work/python-smpplib/smpplib/client.py", line 360, in read_once
    self._alert_notification(pdu)
  File "/home/yevhen/work/python-smpplib/smpplib/client.py", line 296, in _alert_notification
    self.message_received_handler(pdu=pdu)
  File "example.py", line 21, in <lambda>
    lambda pdu: sys.stdout.write('delivered {}\n'.format(pdu.receipted_message_id)))
AttributeError: 'AlertNotification' object has no attribute 'receipted_message_id'
WARNING:smpp.Client.140661104894736:<smpplib.client.Client object at 0x7fee3730e310> was not closed
```

**Comment by eigenein** [comment]
Hi Eugene,

Well, that looks like a bug in the example, and not in the package itself. Indeed, not each PDU class has got the `receipted_message_id` field

**Comment by grmagalhaes** [comment]
In the SMSC of our customer, we receive message_id in pdu.short_message (we have to use split() to extract de message_id). 
receipted_message_id  also returns None.
