### ISSUE TITLE
How to restart after socket disconnect (Question)

### ISSUE THREAD

**Issue by telemix** [python-smpplib/python-smpplib#118]
I send a message (using modified demo code) which works fine. I get my message and all the responses from the carrier. But, after a couple of minutes or so I get the exception "smpplib.exceptions.ConnectionError" from client.listen(). I attempt to restart it as follows (this seems to be the only sequence that does not cause an error) :
```python
    while True:
        try:
            client.listen()
        except smpplib.exceptions.ConnectionError:
            print("Connection closed - trying to restart...")

        # unbind causes smpplib.exceptions.ConnectionError
        # client.unbind()
        client.disconnect()
        client.connect()
        client.bind_transceiver(system_id='xxxxxx', password='xxxxx')
```
Problem is that it then cycles around the following every 5 seconds (see below).

My question is, what should I be doing to reconnect after client.listen() exceptions?

```
Connection closed - trying to restart...
INFO:smpp.Client.140510309433016:Disconnecting...
WARNING:smpp.Client.140510309433016:<smpplib.client.Client object at 0x7fcb1b14beb8> is disconnecting in the bound state
INFO:smpp.Client.140510309433016:Connecting to xxx.xxx.xxx.xxx:pppp ...
DEBUG:smpp.Client.140510309433016:Receiver mode
DEBUG:smpp.Client.140510309433016:Sending bind_transceiver PDU
DEBUG:smpp.Client.140510309433016:>>b'000000270000000900000000000000027874676771383131003624243332394a2b000034000000' (39 bytes)
DEBUG:smpp.Client.140510309433016:Waiting for PDU...
DEBUG:smpp.Client.140510309433016:<<b'000000198000000900000000000000026f7a74657374303100' (25 bytes)
DEBUG:smpp.Client.140510309433016:Read bind_transceiver_resp PDU
DEBUG:smpp.Client.140510309433016:Waiting for PDU...
DEBUG:smpp.Client.140510309433016:Socket timeout, listening again
======================================================================
In EnquireLink
======================================================================
DEBUG:smpp.Client.140510309433016:Sending enquire_link PDU
DEBUG:smpp.Client.140510309433016:>>b'00000010000000150000000000000002' (16 bytes)
DEBUG:smpp.Client.140510309433016:Waiting for PDU...
DEBUG:smpp.Client.140510309433016:<<b'00000010800000150000000000000002' (16 bytes)
======================================================================
In EnquireLink Resp
======================================================================
DEBUG:smpp.Client.140510309433016:Read enquire_link_resp PDU
DEBUG:smpp.Client.140510309433016:Waiting for PDU...
DEBUG:smpp.Client.140510309433016:Socket timeout, listening again
======================================================================
In EnquireLink
======================================================================
DEBUG:smpp.Client.140510309433016:Sending enquire_link PDU
DEBUG:smpp.Client.140510309433016:>>b'00000010000000150000000000000002' (16 bytes)
DEBUG:smpp.Client.140510309433016:Waiting for PDU...
DEBUG:smpp.Client.140510309433016:<<b'00000010800000150000000000000002' (16 bytes)
======================================================================
In EnquireLink Resp
======================================================================
DEBUG:smpp.Client.140510309433016:Read enquire_link_resp PDU
DEBUG:smpp.Client.140510309433016:Waiting for PDU...
DEBUG:smpp.Client.140510309433016:Socket timeout, listening again
======================================================================
In EnquireLink
======================================================================
DEBUG:smpp.Client.140510309433016:Sending enquire_link PDU
DEBUG:smpp.Client.140510309433016:>>b'00000010000000150000000000000002' (16 bytes)
DEBUG:smpp.Client.140510309433016:Waiting for PDU...
DEBUG:smpp.Client.140510309433016:<<b'00000010800000150000000000000002' (16 bytes)
======================================================================
```

**edit** 
Just for completeness, here's the original exception. The carrier logs that we closed the connection : 
```
DEBUG:smpp.Client.140361021165520:Read bind_transceiver_resp PDU
DEBUG:smpp.Client.140361021165520:Waiting for PDU...

Traceback (most recent call last):
  File "demo.py", line 56, in <module>
    client.listen()
  File "/home/davew/clients/telemix/python-smpplib/smpplib/client.py", line 380, in listen
    self.read_once(ignore_error_codes, auto_send_enquire_link)
  File "/home/davew/clients/telemix/python-smpplib/smpplib/client.py", line 329, in read_once
    pdu = self.read_pdu()
  File "/home/davew/clients/telemix/python-smpplib/smpplib/client.py", line 245, in read_pdu
    raise exceptions.ConnectionError()
smpplib.exceptions.ConnectionError
WARNING:smpp.Client.140361021165520:<smpplib.client.Client object at 0x7fa858ce8fd0> was not closed
```

**Comment by telemix** [comment]
I worked it out - I need to recreate the client object : 
```python
client = smpplib.client.Client(IP_ARRESS, PORT, allow_unknown_opt_params=True)
```
and re-initiate the bind on that.

Sorry for the noise.
