### ISSUE TITLE
Unknown status continously being thrown out

### ISSUE THREAD

**Issue by NegassaB** [python-smpplib/python-smpplib#127]
The following error is continously being thrown out and we couldn't debug it. Can you help?
The traceback returned is found below.
```python
Traceback (most recent call last):                                              
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner         
    self.run()                                                                  
  File "/usr/lib/python3.7/threading.py", line 865, in run                      
    self._target(*self._args, **self._kwargs)                                   
  File "/home/pi/sms-api/venv/lib/python3.7/site-packages/smpplib/client.py", li
ne 333, in listen                                                               
    self.read_once(ignore_error_codes)                                          
  File "/home/pi/sms-api/venv/lib/python3.7/site-packages/smpplib/client.py", li
ne 298, in read_once                                                            
    int(pdu.status),                                                            
smpplib.exceptions.PDUError: ('(1375) submit_sm_resp: Unknown status', 1375)  
````

**Comment by eigenein** [comment]
I guess this is a vendor-specific code, right @podshumok ?
