### ISSUE TITLE
tests/ could be better packaged

### ISSUE THREAD

**Issue by kousu** [python-smpplib/python-smpplib#135]
Hey there, thanks for this software. I plan to lean on it soon :)

But if I `pip install smpplib` I end up with a top-level `tests` package that doesn't work:

```
$ python
Python 3.9.2 (default, Feb 20 2021, 18:40:11) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tests.test_gsm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kousu/.local/lib/python3.9/site-packages/tests/test_gsm.py", line 3, in <module>
    import mock
ModuleNotFoundError: No module named 'mock'
>>> 
```

You can see what actually got installed here:

```
$ ls ~/.local/lib/python3.9/site-packages/smpplib
client.py  command_codes.py  command.py  consts.py  exceptions.py  gsm.py  __init__.py	pdu.py	ptypes.py  __pycache__	smpp.py
$ ls ~/.local/lib/python3.9/site-packages/tests/
__init__.py  __pycache__  test_command.py  test_gsm.py
$ cat ~/.local/lib/python3.9/site-packages/smpplib-2.1.0.dist-info/RECORD 
smpplib-2.1.0.dist-info/INSTALLER,sha256=zuuue4knoyJ-UwPPXg8fezS7VCrXJQrAP7zeNuwvFQg,4
smpplib-2.1.0.dist-info/LICENSE,sha256=46mU2C5kSwOnkqkw9XQAJlhBL2JAf1_uCD8lVcXyMRg,7652
smpplib-2.1.0.dist-info/METADATA,sha256=m_PYPcJrG0NHJoKQnaW_LYNmeaefAQf5wDe7POXjWYU,4163
smpplib-2.1.0.dist-info/RECORD,,
smpplib-2.1.0.dist-info/REQUESTED,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
smpplib-2.1.0.dist-info/WHEEL,sha256=-ZFxwj8mZJPIVcZGLrsQ8UGRcxVAOExzPLVBGR7u7bE,92
smpplib-2.1.0.dist-info/top_level.txt,sha256=6f-00aSyR4s-yJi3vQMCBaYCDMMlD5NavUvr2K166U0,14
smpplib-2.1.0.dist-info/zip-safe,sha256=AbpHGcgLb-kRsJGnwFEktk7uzpZOCcBY74-YBdrKVGs,1
smpplib/__init__.py,sha256=IsNibfXn_AXnYAZcRWM36cSLhNgGyLhMhHtLbNaZcuY,958
smpplib/__pycache__/__init__.cpython-39.pyc,,
smpplib/__pycache__/client.cpython-39.pyc,,
smpplib/__pycache__/command.cpython-39.pyc,,
smpplib/__pycache__/command_codes.cpython-39.pyc,,
smpplib/__pycache__/consts.cpython-39.pyc,,
smpplib/__pycache__/exceptions.cpython-39.pyc,,
smpplib/__pycache__/gsm.cpython-39.pyc,,
smpplib/__pycache__/pdu.cpython-39.pyc,,
smpplib/__pycache__/ptypes.cpython-39.pyc,,
smpplib/__pycache__/smpp.cpython-39.pyc,,
smpplib/client.py,sha256=Ag89el_XlQczaRdNyivu-YCOZpWxvl4YmB8A6h3NYwY,12510
smpplib/command.py,sha256=Xq01JDhV09Zd4K5tWuiAgjnodI9K-3_KWyg-9_yhkk8,33803
smpplib/command_codes.py,sha256=9cNJyROwQAFaTLwvm7BGMmm1b1UjuOdIeEjKLqX8EMM,1633
smpplib/consts.py,sha256=HLlobB8psWjlT14bknIVLUYrgK3IWznjrvpw8pTQsK8,13991
smpplib/exceptions.py,sha256=QIn2TX0XtYYS8sHdzGUKKTsRpqO3kdWl-ZaY62Zkiyk,311
smpplib/gsm.py,sha256=pG4DGHDX5cc-sHQYuW_lLMWgbt3i2Ce6aceepKqpRw8,3496
smpplib/pdu.py,sha256=FhkimxpJVbG25GHkuuRahIaSHJdFURY0QvA1hiD533g,4011
smpplib/ptypes.py,sha256=ryRmMQmXg9E8u6x6U2HaL2E_puQq7zeO3-DGoe9ZLt8,1108
smpplib/smpp.py,sha256=BAtb0SzNVu3qRM1zweRDalXja38p2rVazFTmEFVntNk,1317
tests/__init__.py,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
tests/__pycache__/__init__.cpython-39.pyc,,
tests/__pycache__/test_command.cpython-39.pyc,,
tests/__pycache__/test_gsm.cpython-39.pyc,,
tests/test_command.py,sha256=glbsaDtrw9spTK3J3daAkz_yCvboid-HFy47bF_6bKI,1054
tests/test_gsm.py,sha256=vcRbSTz5pLLyc6RgmqsPzkbEXroSdWeuslu0RmYHnuo,2197
```

This is a known bug in python packaging that everyone has to work around, unfortunately:

* https://github.com/pypa/packaging.python.org/issues/320#issuecomment-495990983
* https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure
* https://hynek.me/articles/testing-packaging/

I know of two workarounds, Either

1. Use `packages=find_packages(exclude=['tests'])` in 

    https://github.com/python-smpplib/python-smpplib/blob/29e611d20b21c4c6aff55ee867f2355f4c7085c8/setup.py#L12

    or maybe `packages=find_packages('smpplib/')`.

2. Switch to a `src/` layout (in the links above), with `mkdir src && git mv smpplib src && git mv tests src/smpplib` and then do 

    ```
    packages=find_packages('src/'])
    package_dir={"":"src/"},
    ```

Also, `tests_require` is deprecated (https://github.com/pypa/setuptools/issues/1684). The recommendation from on high is now to use `extras_require` like this (https://github.com/pypa/setuptools/issues/1684#issuecomment-648441338):

```
extras_require={
    'tests': ['pytest', 'mock', 'tox'],
    },
```

and then instead of 

https://github.com/python-smpplib/python-smpplib/blob/29e611d20b21c4c6aff55ee867f2355f4c7085c8/tox.ini#L6-L8

write

```
extras = tests
```

**Comment by podshumok** [comment]
Thanks! Can you please check if version from the #136 works for you?

**Comment by kousu** [comment]
Thanks for taking care of this :)

**Comment by eigenein** [comment]
Tracked in #136.
