### ISSUE TITLE
Problems when unbinding

### ISSUE THREAD

**Issue by dotpmrcunha** [python-smpplib/python-smpplib#19]
Hi,

I am currently reading 12 bytes from unbind PDU Response, when I should in fact read 16 bytes. I also check the pcap packets and the information is there. 

Here is the debug trace:

```
SEND BIND
DEBUG:smpplib.client:Sending bind_transceiver PDU
DEBUG:smpplib.client:>>000000250000000900000000000000014d324d004d65646f31735700534d50500034000000 (37 bytes)
DEBUG:smpplib.client:Waiting for PDU...
DEBUG:smpplib.client:<<0000001780000009000000000000000130000210000134 (23 bytes)
DEBUG:smpplib.client:Read bind_transceiver_resp PDU
DEBUG:smpplib.client:Waiting for PDU...

SEND UNBIND
DEBUG:smpplib.client:>>00000010000000060000000000000001 (16 bytes)
DEBUG:smpplib.client:Waiting for PDU...
DEBUG:smpplib.client:<<000000100000000000000001 (12 bytes)

INFO:werkzeug:127.0.0.1 - - [03/Mar/2016 17:45:24] "GET /close-app/ HTTP/1.1" 200 -
ERROR
:smpp-app.SMPPApp: Unknown SMPP command code '0x0' - Continue operating.: 
 Traceback (most recent call last):
  File "/home/m2m/smpp-app/SMPPApp.py", line 78, in listen
    client.listen()
  File "/home/Envs/dev1/lib/python2.7/site-packages/smpplib/client.py", line 275, in listen
    p = self.read_pdu()
  File "/home/Envs/dev1/lib/python2.7/site-packages/smpplib/client.py", line 218, in read_pdu
    p = smpp.parse_pdu(raw_pdu, client=self)
  File "/home/Envs/dev1/lib/python2.7/site-packages/smpplib/smpp.py", line 40, in parse_pdu
    command = pdu.extract_command(data)
  File "/home/Envs/dev1/lib/python2.7/site-packages/smpplib/pdu.py", line 38, in extract_command
    return command_codes.get_command_name(code)
  File "/home/Envs/dev1/lib/python2.7/site-packages/smpplib/command_codes.py", line 46, in get_command_name
    "'0x%x'" % code)
UnknownCommandError: Unknown SMPP command code '0x0'

DEBUG:smpplib.client:Waiting for PDU...
INFO:smpplib.client:Connecting to 10.5.13.13:38116...
```

---

I printed the `length` variable in `read_pdu` and is also `16`.

---

Here is the pcap packets from the unbind transaction: 

```
Frame 317: 82 bytes on wire (656 bits), 82 bytes captured (656 bits)
Transmission Control Protocol, Src Port: 36097 (36097), Dst Port: 38116 (38116), Seq: 54, Ack: 40, Len: 16
Short Message Peer to Peer, Command: Unbind, Seq: 1, Len: 16
    Length: 16
    Operation: Unbind (0x00000006)
    Sequence #: 1

Frame 318: 82 bytes on wire (656 bits), 82 bytes captured (656 bits)
Transmission Control Protocol, Src Port: 38116 (38116), Dst Port: 36097 (36097), Seq: 40, Ack: 70, Len: 16
Short Message Peer to Peer, Command: Unbind - resp, Status: "Ok", Seq: 1, Len: 16
    Length: 16
    Operation: Unbind - resp (0x80000006)
    Result: Ok (0x00000000)
    Sequence #: 1
```

**Comment by norguhtar** [comment]
I'm get like this error. Got 

DEBUG:smpp server:HEX: 000000ca000000050000000000000001000101373931323532373837363900000131363838000400000000000000007869643a303361333762323735366662386665373030303561313563207375623a303031
20646c7672643a303030207375626d697420646174653a31363033333030383335353120646f6e6520646174653a31363033333030383335353220737461743a44454c49565244206572723a30303020746578743a001e001930336133376
2323735366662386665373030303561313563000427000102000000ca000000050000000000000002000101373931323532373837363900000131363838000400000000000000007869643a30336133376233663536666238666539303030
3465353237207375623a30303120646c7672643a303030207375626d697420646174653a31363033333030383335353320646f6e6520646174653a31363033333030383335353320737461743a44454c49565244206572723a30303020746
578743a001e0019303361333762336635366662386665393030303465353237000427000102000000ca000000050000000000000003000101373931323532373837363900000131363838000400000000000000007869643a303361333762
343935366662386665623030303339636364207375623a30303120646c7672643a303030207375626d697420646174653a31363033333030383335353520646f6e6520646174653a31363033333030383335353420737461743a44454c495
65244206572723a30303020746578743a001e0019303361333762343935366662386665623030303339636364000427000102                                                                                        
Unhandled Error                                                                                                                                                                              
Traceback (most recent call last):                                                                                                                                                           
  File "/usr/lib64/python2.6/site-packages/twisted/python/log.py", line 101, in callWithLogger                                                                                               
    return callWithContext({"system": lp}, func, *args, **kw)                                                                                                                                
  File "/usr/lib64/python2.6/site-packages/twisted/python/log.py", line 84, in callWithContext                                                                                               
    return context.call({ILogContext: newCtx}, func, *args, **kw)                                                                                                                            
  File "/usr/lib64/python2.6/site-packages/twisted/python/context.py", line 118, in callWithContext                                                                                          
    return self.currentContext().callWithContext(ctx, func, *args, **kw)                                                                                                                     
  File "/usr/lib64/python2.6/site-packages/twisted/python/context.py", line 81, in callWithContext                                                                                           
    return func(*args,**kw)                                                                                                                                                                  
--- <exception caught here> ---                                                                                                                                                              
  File "/usr/lib64/python2.6/site-packages/twisted/internet/posixbase.py", line 611, in _doReadOrWrite                                                                                       
    why = selectable.doRead()                                                                                                                                                                
  File "/usr/lib64/python2.6/site-packages/twisted/internet/tcp.py", line 209, in doRead                                                                                                     
    return self._dataReceived(data)                                                                                                                                                          
  File "/usr/lib64/python2.6/site-packages/twisted/internet/tcp.py", line 215, in _dataReceived                                                                                              
    rval = self.protocol.dataReceived(data)                                                                                                                                                  
  File "./twisted-client.py", line 197, in dataReceived                                                                                                                                      
    pdu = smpp.parse_pdu(data, client=self)                                                                                                                                                  
  File "/usr/lib/python2.6/site-packages/python_smpplib-1.0.1-py2.6.egg/smpplib/smpp.py", line 46, in parse_pdu                                                                              
    new_pdu.parse(data)                                                                                                                                                                      
  File "/usr/lib/python2.6/site-packages/python_smpplib-1.0.1-py2.6.egg/smpplib/pdu.py", line 133, in parse                                                                                  
    self.parse_params(data[16:])                                                                                                                                                             
  File "/usr/lib/python2.6/site-packages/python_smpplib-1.0.1-py2.6.egg/smpplib/command.py", line 332, in parse_params                                                                       
    self.parse_optional_params(data[pos:])                                                                                                                                                   
  File "/usr/lib/python2.6/site-packages/python_smpplib-1.0.1-py2.6.egg/smpplib/command.py", line 347, in parse_optional_params                                                              
    field = get_optional_name(type_code)                                                                                                                                                     
  File "/usr/lib/python2.6/site-packages/python_smpplib-1.0.1-py2.6.egg/smpplib/command.py", line 73, in get_optional_name                                                                   
    'Unknown SMPP command code "0x%x"' % code)                                                                                                                                               
smpplib.exceptions.UnknownCommandError: Unknown SMPP command code "0x0"

**Comment by dotpmrcunha** [comment]
Bump

**Comment by podshumok** [comment]
I'm afraid currently there is no one who can look at it.
PRs are welcome though.

**Comment by eigenein** [comment]
Hi @dotpmrcunha,

12 bytes is fine because `length` includes the `length` field itself (4 bytes). If you look at the [definition of `unbind`](https://www.activexperts.com/sms-component/smpp-specifications/smpp-pdu-definition/#unbind_operation), the rest takes 12 bytes.

**Comment by eigenein** [comment]
Hmmm, tricky one. Command ID of `0x00000000` is indeed not defined in the standard. Furthermore, command status of `1` means `Message Length is invalid`.
