### ISSUE TITLE
Broken PDU

### ISSUE THREAD

**Issue by mdonalisio** [python-smpplib/python-smpplib#22]
```
INFO:smpplib.client:Connecting to 192.168.0.15:8023...
bind_transceiver
DEBUG:smpplib.client:Receiver mode
DEBUG:smpplib.client:Sending bind_transceiver PDU
DEBUG:smpplib.client:>>0000001f000000090000000000000001766f69700031323334000034000000 (31 bytes)
DEBUG:smpplib.client:Waiting for PDU...
WARNING:smpplib.client:Receive broken pdu... '\r\n'
Traceback (most recent call last):
  File "sample.py", line 23, in <module>
    client.bind_transceiver(system_id='voip', password='1234')
  File "/home/smsserver/smpplib/client.py", line 151, in bind_transceiver
    return self._bind('bind_transceiver', **kwargs)
  File "/home/smsserver/smpplib/client.py", line 132, in _bind
    resp = self.read_pdu()
  File "/home/smsserver/smpplib/client.py", line 212, in read_pdu
    raise exceptions.PDUError('Broken PDU')
smpplib.exceptions.PDUError: Broken PDU
WARNING:smpplib.client:Command unbind failed: Incorrect BIND Status for given command. Ignored
INFO:smpplib.client:Disconnecting...
```

**Comment by eigenein** [comment]
Looks like SMSC returned `'\r\n'` instead of a valid PDU. Is this still an issue?
