### ISSUE TITLE
 smpplib.exceptions.PDUError: ('(8) bind_transmitter_resp: System Error', 8)

### ISSUE THREAD

**Issue by ernest-andela** [python-smpplib/python-smpplib#85]
I am getting the error below without any information to debug 

```
[Sun Jun 02 16:27:10.311791 2019] [:error] [pid 23109] DEBUG:smpplib.client:Sending bind_transmitter PDU
[Sun Jun 02 16:27:10.312102 2019] [:error] [pid 23109] DEBUG:smpplib.client:>>b'0000002700000002000000000000000161657261536f6674006165726173403132000034000000' (39 bytes)
[Sun Jun 02 16:27:10.312259 2019] [:error] [pid 23109] DEBUG:smpplib.client:Waiting for PDU...
[Sun Jun 02 16:27:10.518167 2019] [:error] [pid 23109] DEBUG:smpplib.client:<<b'0000001180000002000000080000000100' (17 bytes)
[Sun Jun 02 16:27:10.518501 2019] [:error] [pid 23109] DEBUG:smpplib.client:Read bind_transmitter_resp PDU
[Sun Jun 02 16:27:10.518665 2019] [:error] [pid 23109] INFO:smpplib.client:Disconnecting...
[Sun Jun 02 16:27:10.541386 2019] [:error] [pid 23109] [remote 154.160.26.113:0] mod_wsgi (pid=23109): Exception occurred processing WSGI script '/opt/python/current/app/wsgi.py'.
[Sun Jun 02 16:27:10.542715 2019] [:error] [pid 23109] DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): sentry.io:443
[Sun Jun 02 16:27:10.544209 2019] [:error] [pid 23109] [remote 154.160.26.113:0] Traceback (most recent call last):
[Sun Jun 02 16:27:10.544379 2019] [:error] [pid 23109] [remote 154.160.26.113:0]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/sentry_sdk/integrations/flask.py", line 66, in sentry_patched_wsgi_app
client.bind_transmitter(system_id=SMS_TIGO_USERNAME, password=SMS_TIGO_PASSWORD)
[Sun Jun 02 16:27:10.546016 2019] [:error] [pid 23109] [remote 154.160.26.113:0]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/smpplib/client.py", line 149, in bind_transmitter
[Sun Jun 02 16:27:10.546051 2019] [:error] [pid 23109] [remote 154.160.26.113:0]     return self._bind('bind_transmitter', **kwargs)
[Sun Jun 02 16:27:10.546088 2019] [:error] [pid 23109] [remote 154.160.26.113:0]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/smpplib/client.py", line 143, in _bind
[Sun Jun 02 16:27:10.546127 2019] [:error] [pid 23109] [remote 154.160.26.113:0]     int(resp.status),
[Sun Jun 02 16:27:10.546177 2019] [:error] [pid 23109] [remote 154.160.26.113:0] smpplib.exceptions.PDUError: ('(8) bind_transmitter_resp: System Error', 8)
```

**Comment by eigenein** [comment]
This indicates a system error occurred on SMSC side while running the command and described in the SMPP specs under `ESME_RSYSERR`:

> System Error.
> MC system error indicating that all or part
> of the MC is currently unavailable. This
> can be returned in any response PDU. 

I assume you'll need to check the SMSC logs to know what happened there because specific error is not available on a client side

**Comment by eigenein** [comment]
Did you solve your issue?

**Comment by Mohammed12Khair** [comment]
I have same issue ,using correct bind and correct system is and password but  still getting error 15 


  client.bind_transmitter(system_id=SYSTEM_ID, password=SYSTEM_PASS)
  File "/home/server/.local/lib/python3.7/site-packages/smpplib/client.py", line 149, in bind_transmitter
    return self._bind('bind_transmitter', **kwargs)
  File "/home/server/.local/lib/python3.7/site-packages/smpplib/client.py", line 143, in _bind
    int(resp.status),
smpplib.exceptions.PDUError: ('(15) bind_transmitter_resp: Invalid System ID', 15)
<smpplib.client.Client object at 0x7f4a8ab61d68> was not closed

**Comment by eigenein** [comment]
This is a different error, @Mohammed12Khair. Your SMPP gateway returns "Invalid System ID", so you need to check with them.

**Comment by Mohammed12Khair** [comment]
@eigenein ,srry i just solved my issue ,i missed parameter => (system_type='smpp'), now its working fine,

thanks a lot
