### ISSUE TITLE
can't concat str to bytes

### ISSUE THREAD

**Issue by ernest-andela** [python-smpplib/python-smpplib#86]
I am getting this error below, everything is working expect this part of the code:

```
  File "smpplib/client.py", line 347, in send_message
    self.send_pdu(ssm)
  File "smpplib/client.py", line 181, in send_pdu
    generated = p.generate()
  File "smpplib/pdu.py", line 136, in generate
    body = self.generate_params()
  File "smpplib/command.py", line 145, in generate_params
    body += value
```

**Comment by ernest-andela** [comment]
Having same issue here:

```
  File "smpplib/client.py", line 347, in send_message
    self.send_pdu(ssm)
  File "smpplib/client.py", line 181, in send_pdu
    generated = p.generate()
  File "smpplib/pdu.py", line 136, in generate
    body = self.generate_params()
  File "smpplib/command.py", line 140, in generate_params
    value = self._generate_string(field)
  File "smpplib/command.py", line 176, in _generate_string
    value = field_value + chr(0)
```

**Comment by eigenein** [comment]
Could you show us the corresponding call (replacing a sensitive data with some `X`s)? I assume some field expects byte string instead of string

**Comment by ernest-andela** [comment]
```
                client.bind_transceiver(system_id=XXXXX, password=XXXXX)
                client.send_message(
                    source_addr_ton=smpplib.consts.SMPP_TON_ALNUM,
                    source_addr='XXXXX',
                    dest_addr_ton=smpplib.consts.SMPP_TON_INTL,
                    destination_addr='XXXXX',
                    registered_delivery=True,
                    short_message="test Message",
                    data_coding=self.encoding_flag,
                    esm_class=self.msg_type_flag)
```

**Comment by eigenein** [comment]
To my best knowledge, `short_message` should be a byte string, it's directly concatenated to a binary packet. I also suggest you to use `smpplib.gsm.make_parts(text)` to properly encode string to SMS encoding like `README` does

**Comment by ernest-andela** [comment]
Per your suggestions, l am doing the following :

```
parts, encoding_flag, msg_type_flag = smpplib.gsm.make_parts(u'testing message\n' *10)
        for part in self.parts:
            # print("PRINTING PATHS==> ", part)
            pdu = client.send_message(
                source_addr_ton=smpplib.consts.SMPP_TON_ALNUM,
                source_addr=bytes("XXXXXXX", 'utf-8'),
                dest_addr_ton=smpplib.consts.SMPP_TON_INTL,
                destination_addr=bytes("XXXXXXX, 'utf-8'),
                short_message=part,
                data_coding=self.encoding_flag,
                esm_class=self.msg_type_flag,
                registered_delivery=True,
            )
```

**Comment by eigenein** [comment]
Does it fail like that?

`source_addr` and `destination_addr` should be fine as strings, by the way

**Comment by ernest-andela** [comment]
Below is the error:

```

[Tue Jun 04 08:54:19.850535 2019] [:error] [pid 18054] INFO:smpplib.client:Connecting to XXXXXXXXXXXXXXX...
[Tue Jun 04 08:54:19.978966 2019] [:error] [pid 18054] DEBUG:smpplib.client:Receiver mode
[Tue Jun 04 08:54:19.979202 2019] [:error] [pid 18054] DEBUG:smpplib.client:Sending bind_transceiver PDU
[Tue Jun 04 08:54:19.979416 2019] [:error] [pid 18054] DEBUG:smpplib.client:>>b'0000002700000009000000000000000161657261536f6674006165726173403132000034000000' (39 bytes)
[Tue Jun 04 08:54:19.979572 2019] [:error] [pid 18054] DEBUG:smpplib.client:Waiting for PDU...
[Tue Jun 04 08:54:20.108661 2019] [:error] [pid 18054] DEBUG:smpplib.client:<<b'0000001180000009000000000000000100' (17 bytes)
[Tue Jun 04 08:54:20.108998 2019] [:error] [pid 18054] DEBUG:smpplib.client:Read bind_transceiver_resp PDU
[Tue Jun 04 08:54:20.109263 2019] [:error] [pid 18054] DEBUG:smpplib.client:Sending submit_sm PDU
[Tue Jun 04 08:54:20.109544 2019] [:error] [pid 18054] DEBUG:smpplib.client:>>b'000000c300000004000000000000000200050032333332343035373938383400010030323430353739383834004000000000010008008c050003c50201041f044004380432043504420020043c043804400021000a041f044004380432043504420020043c043804400021000a041f044004380432043504420020043c043804400021000a041f044004380432043504420020043c043804400021000a041f044004380432043504420020043c043804400021000a041f044004380432043504420020' (195 bytes)
[Tue Jun 04 08:54:20.109656 2019] [:error] [pid 18054] pdu.sequence 2
[Tue Jun 04 08:54:20.109852 2019] [:error] [pid 18054] DEBUG:smpplib.client:Sending submit_sm PDU
[Tue Jun 04 08:54:20.110092 2019] [:error] [pid 18054] DEBUG:smpplib.client:>>b'000000a7000000040000000000000003000500323333323430353739383834000100303234303537393838340040000000000100080070050003c50202043c043804400021000a041f044004380432043504420020043c043804400021000a041f044004380432043504420020043c043804400021000a041f044004380432043504420020043c043804400021000a041f044004380432043504420020043c043804400021000a' (167 bytes)
[Tue Jun 04 08:54:20.110192 2019] [:error] [pid 18054] pdu.sequence 3
[Tue Jun 04 08:54:20.110310 2019] [:error] [pid 18054] DEBUG:smpplib.client:Waiting for PDU...
[Tue Jun 04 08:54:20.714709 2019] [:error] [pid 18054] DEBUG:smpplib.client:<<b'0000001b80000004000000a9000000033234333634393233373400' (27 bytes)
[Tue Jun 04 08:54:20.715039 2019] [:error] [pid 18054] DEBUG:smpplib.client:Read submit_sm_resp PDU
[Tue Jun 04 08:54:20.737519 2019] [:error] [pid 18054] [remote 154.160.24.243:0] mod_wsgi (pid=18054): Exception occurred processing WSGI script '/opt/python/current/app/wsgi.py'.
[Tue Jun 04 08:54:20.738788 2019] [:error] [pid 18054] DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): sentry.io:443
[Tue Jun 04 08:54:20.740202 2019] [:error] [pid 18054] [remote 154.160.24.243:0] Traceback (most recent call last):
[Tue Jun 04 08:54:20.740370 2019] [:error] [pid 18054] [remote 154.160.24.243:0]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/sentry_sdk/integrations/flask.py", line 66, in sentry_patched_wsgi_app
[Tue Jun 04 08:54:20.740475 2019] [:error] [pid 18054] [remote 154.160.24.243:0]     environ, start_response
[Tue Jun 04 08:54:20.740544 2019] [:error] [pid 18054] [remote 154.160.24.243:0]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/sentry_sdk/integrations/wsgi.py", line 91, in __call__
[Tue Jun 04 08:54:20.740598 2019] [:error] [pid 18054] [remote 154.160.24.243:0]     reraise(*_capture_exception(hub))
[Tue Jun 04 08:54:20.740649 2019] [:error] [pid 18054] [remote 154.160.24.243:0]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/sentry_sdk/_compat.py", line 52, in reraise
[Tue Jun 04 08:54:20.740707 2019] [:error] [pid 18054] [remote 154.160.24.243:0]     raise value
[Tue Jun 04 08:54:20.740756 2019] [:error] [pid 18054] [remote 154.160.24.243:0]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/sentry_sdk/integrations/wsgi.py", line 89, in __call__
[Tue Jun 04 08:54:20.740810 2019] [:error] [pid 18054] [remote 154.160.24.243:0]     rv = self.app(environ, start_response)
[Tue Jun 04 08:54:20.740871 2019] [:error] [pid 18054] [remote 154.160.24.243:0]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/sentry_sdk/integrations/flask.py", line 65, in <lambda>
[Tue Jun 04 08:54:20.740922 2019] [:error] [pid 18054] [remote 154.160.24.243:0]     return SentryWsgiMiddleware(lambda *a, **kw: old_app(self, *a, **kw))(
[Tue Jun 04 08:54:20.741085 2019] [:error] [pid 18054] [remote 154.160.24.243:0]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
[Tue Jun 04 08:54:20.741130 2019] [:error] [pid 18054] [remote 154.160.24.243:0]     return self.wsgi_app(environ, start_response)
[Tue Jun 04 08:54:20.741171 2019] [:error] [pid 18054] [remote 154.160.24.243:0]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
[Tue Jun 04 08:54:20.741205 2019] [:error] [pid 18054] [remote 154.160.24.243:0]     response = self.handle_exception(e)
[Tue Jun 04 08:54:20.741242 2019] [:error] [pid 18054] [remote 154.160.24.243:0]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
[Tue Jun 04 08:54:20.741276 2019] [:error] [pid 18054] [remote 154.160.24.243:0]     reraise(exc_type, exc_value, tb)
[Tue Jun 04 08:54:20.741312 2019] [:error] [pid 18054] [remote 154.160.24.243:0]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
[Tue Jun 04 08:54:20.741346 2019] [:error] [pid 18054] [remote 154.160.24.243:0]     raise value
[Tue Jun 04 08:54:20.741382 2019] [:error] [pid 18054] [remote 154.160.24.243:0]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
[Tue Jun 04 08:54:20.741415 2019] [:error] [pid 18054] [remote 154.160.24.243:0]     response = self.full_dispatch_request()
[Tue Jun 04 08:54:20.741452 2019] [:error] [pid 18054] [remote 154.160.24.243:0]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
[Tue Jun 04 08:54:20.741485 2019] [:error] [pid 18054] [remote 154.160.24.243:0]     rv = self.handle_user_exception(e)
[Tue Jun 04 08:54:20.741521 2019] [:error] [pid 18054] [remote 154.160.24.243:0]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
[Tue Jun 04 08:54:20.741555 2019] [:error] [pid 18054] [remote 154.160.24.243:0]     reraise(exc_type, exc_value, tb)
[Tue Jun 04 08:54:20.741590 2019] [:error] [pid 18054] [remote 154.160.24.243:0]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
[Tue Jun 04 08:54:20.741624 2019] [:error] [pid 18054] [remote 154.160.24.243:0]     raise value
[Tue Jun 04 08:54:20.741658 2019] [:error] [pid 18054] [remote 154.160.24.243:0]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
[Tue Jun 04 08:54:20.741702 2019] [:error] [pid 18054] [remote 154.160.24.243:0]     rv = self.dispatch_request()
[Tue Jun 04 08:54:20.741739 2019] [:error] [pid 18054] [remote 154.160.24.243:0]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
[Tue Jun 04 08:54:20.741774 2019] [:error] [pid 18054] [remote 154.160.24.243:0]     return self.view_functions[rule.endpoint](**req.view_args)
[Tue Jun 04 08:54:20.741878 2019] [:error] [pid 18054] [remote 154.160.24.243:0]   File "/opt/sms_operation.py", line 152, in connect_XXXXX
[Tue Jun 04 08:54:20.741912 2019] [:error] [pid 18054] [remote 154.160.24.243:0]     client.listen()
[Tue Jun 04 08:54:20.741947 2019] [:error] [pid 18054] [remote 154.160.24.243:0]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/smpplib/client.py", line 333, in listen
[Tue Jun 04 08:54:20.741980 2019] [:error] [pid 18054] [remote 154.160.24.243:0]     self.read_once(ignore_error_codes)
[Tue Jun 04 08:54:20.742015 2019] [:error] [pid 18054] [remote 154.160.24.243:0]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/smpplib/client.py", line 298, in read_once
[Tue Jun 04 08:54:20.742048 2019] [:error] [pid 18054] [remote 154.160.24.243:0]     int(pdu.status),
[Tue Jun 04 08:54:20.742096 2019] [:error] [pid 18054] [remote 154.160.24.243:0] smpplib.exceptions.PDUError: ('(169) submit_sm_resp: Unknown status', 169)

```

**Comment by ernest-andela** [comment]
I finally got it working. however, it only works when l call this client.listen()

**Comment by eigenein** [comment]
I couldn't find 169 in the specs, though some resources suggest it's the "bad format" error. Indeed, what I noticed in the logs, that there is no `Waiting for PDU` after sending the first part. `client.listen()` is actually reading incoming PDUs. Could be that you can't send the next part until you read a confirmation of the first part

**Comment by ernest-andela** [comment]
Thanks. I got it working. So it means this has to be running always client.listen()? Also, how do l restart it? or close the listening ?

**Comment by eigenein** [comment]
It's a normal loop, so once it ended you get execution back. Or you can wrap it into a thread to get a finer control.

Another option is to call `client.read_pdu` manually after you make a command call

**Comment by ernest-andela** [comment]
Sweet.. Thanks a lot. Also my handlers are not being called .set_message_sent_handler(lambda pdu: print('sent {} {}\n'.format(pdu.sequence, pdu.message_id))). I can see WARNING:smpplib.client:Message sent handler (Override me)

**Comment by eigenein** [comment]
It means that `client.message_sent_handler` is still the defaukt one. Make sure you set it before you call `listen()`

**Comment by ernest-andela** [comment]
Ok. Thanks a lot. What does this mean ('(8) bind_transceiver_resp: System Error', 8)? I have contacted the Telecom company and keep saying l should send the tcpdump, and they have not been able to figure this out. Does it mean the issue is from my side or from the Telecom company? Also, they sent me their error code list and error code 8 is not part.

**Comment by eigenein** [comment]
> MC system error indicating that all or part of the MC is currently unavailable. This can be returned in any response PDU.

Please, point them to the SMPP specs, chapter 4.7.6. Error code 8 aka `ESME_RSYSERR` is a part of the standard. Their message centre should be compatible with it as well

Without information from their side it's not possible to say which side the issue is from, as they're returning the error

**Comment by ernest-andela** [comment]
Thanks a lot. I told them and they are asking me of **System type**?

**Comment by eigenein** [comment]
"System type" is something that you specify in `bind_transceiver` call, there's `system_type=...` parameter for that. Specs:

> Identifies the type of ESME system requesting to bind as a transceiver with the SMSC.
> The `system_type` (optional) may be used to categorise the system, e.g., “EMAIL”, “WWW”, etc.

Check with them, what's the correct value for their gateway

**Comment by ernest-andela** [comment]
I finally figured out what the issue is. When l first deploy my application to the server and l send the sms and l call this client.listen() to listen. Subsequent sms causes the system error unless l deploy the application again to to recreate the client. Am suspecting this client.listen() is causing the issue because when l call pdu = client.read_pdu() instead of client.listen(). My worry is how do l know if the sms has been sent or received

**Comment by eigenein** [comment]
Take a look at #26

**Comment by ernest-andela** [comment]
Thanks @eigenein Please how l am supposed to know if the message has actually been delivered or failed, because this **receipted_message_id** is always None for me?   Is it possible to get the parse data from the SMSC server ?

DEBUG:smpplib.client:Read deliver_sm PDU
DEBUG:smpplib.client:Sending deliver_sm_resp PDU

**Comment by eigenein** [comment]
If `receipted_message_id` was there in a packet, it would've been parsed; this is actually tested by the unit test you referred to. I'm afraid, your SMSc just doesn't send this information. Could you check with their support if that's the case?
